version: "3"

services:
  node:
    image: node:14
    user: node
    container_name: node-14
    working_dir: /usr/src/zipme
    environment:
      - NODE_ENV=test
    command: yarn run start
    volumes:
      - .:/usr/src/zipme
    ports:
      - '4200:4200'
